### ISSUE TITLE
no way to directly power with a 3.3V regulated input?

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/MicroMod_Data_Logging_Carrier#5]
I looked at the schematics of this board; is it correct that there is no way to directly power the board with the 3.3V regulated output that typically comes out of a step up step down converter? If this is correct this is very sad, as this drastically limits the usability of the board :( .

**Comment by nseidle** [comment]
Because there are three power rails on the board (3.3V to the processor, 3.3V to Qwiic, 3.3V to SD all powered from VIN), your options are limited. If all you need is power to a processor board I'd recommend cutting and soldering to the MEAS jumper. This would allow you to inject your 3.3V source directly.

![image](https://user-images.githubusercontent.com/117102/150821386-74bb9032-4181-42c3-b3aa-25983ee71aba.png)
